import os
import dj_database_url
from pathlib import Path
from decouple import config

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INSTALLED_APPS = [
    'jazzmin',  # MUST BE FIRST
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gym',
    'website',

]

JAZZMIN_SETTINGS = {

    # Title on browser tab
    "site_title": "GymPilot Admin",

    # Top left header
    "site_header": "GymPilot Control Panel",

    # Brand name (sidebar top)
    "site_brand": "GYMPILOT",

    # Welcome text on login page
    "welcome_sign": "Welcome to GymPilot SuperAdmin",

    # Copyright text
    "copyright": "GymPilot",

    # Sidebar style
    "navigation_expanded": True,

    # Icons (FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "gym.Gym": "fas fa-dumbbell",
        "gym.Member": "fas fa-user-friends",
        "gym.MembershipPlan": "fas fa-layer-group",
        "gym.Subscription": "fas fa-id-card",
        "gym.Payment": "fas fa-credit-card",
    },

    # Sidebar colors
    "sidebar": "sidebar-dark-primary",

    # Topbar color
    "topbar": "navbar-dark",

    # Show UI builder (optional)
    "show_ui_builder": False,
}

"""
Django settings for project_r project.
Generated by Django 6.0.2
"""


# ======================================================
# BASE DIRECTORY
# ======================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ======================================================
# SECURITY
# ======================================================
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=True, cast=bool)


#ALLOWED_HOSTS = ['*']


# ======================================================
# AUTO LOGOUT
SESSION_COOKIE_AGE = 3600      # 1 hour auto logout
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#SESSION_SAVE_EVERY_REQUEST = True

# ======================================================




# ======================================================
# MIDDLEWARE
# ======================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # Static files server for Render
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # Required for login forms
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # Messages + UI
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# ======================================================
# URLS
# ======================================================

ROOT_URLCONF = 'project_r.urls'


# ======================================================
# TEMPLATES
# ======================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Optional global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ======================================================
# WSGI
# ======================================================

WSGI_APPLICATION = 'project_r.wsgi.application'


# ======================================================
# DATABASE
# ======================================================



# ======================================================
# DATABASE
# ======================================================

DATABASES = {
    "default": dj_database_url.parse(
        config("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True
    )
}

DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
# ======================================================
# PASSWORD VALIDATION
# ======================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ======================================================
# INTERNATIONALIZATION
# ======================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # India timezone

USE_I18N = True
USE_TZ = True


# ======================================================
# AUTH SETTINGS (Gym Owner)
# ======================================================

#LOGIN_URL = '/login/'
LOGIN_URL = 'gym:owner_login'
LOGIN_REDIRECT_URL = 'gym:dashboard'
LOGOUT_REDIRECT_URL = 'gym:owner_login'


#LOGIN_REDIRECT_URL = '/'



# ======================================================
# EMAIL (For Forgot Password)
# ======================================================

# Development mode → reset link prints in terminal
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production (later you will replace with SMTP)


# ======================================================
# DEFAULT AUTO FIELD
# ======================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ======================================================
# STATIC FILES (CLEAN CONFIG)
# ======================================================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ======================================================
# ALLOWED HOSTS
# ======================================================

ALLOWED_HOSTS = ['*'] if DEBUG else [
    "127.0.0.1", "localhost",
    'gympilot.online',
    'www.gympilot.online',
    '.onrender.com'
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"


# ======================================================
# CSRF TRUSTED ORIGINS
# ======================================================

CSRF_TRUSTED_ORIGINS = [
    'https://gympilot.online',
    'https://www.gympilot.online',
    'https://*.onrender.com'
]

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

