# Generated by Django 6.0.2 on 2026-03-01 10:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='member_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Enter valid Indian mobile number')]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.member'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.membershipplan'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('expiry_date__gte', datetime.date(2026, 3, 1))), fields=('member',), name='one_active_subscription_per_member'),
        ),
    ]
