# Generated by Django 6.0.2 on 2026-03-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paid_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
