# Generated by Django 6.0.2 on 2026-02-18 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_subscription_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
