# Generated by Django 6.0.2 on 2026-03-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_payment_billing_end_payment_billing_start_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='one_active_subscription_per_member',
        ),
    ]
