# Generated by Django 6.0.2 on 2026-03-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_subscription_paid_on'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='one_subscription_per_member_per_gym',
        ),
    ]
