# Generated by Django 6.0.2 on 2026-03-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_remove_subscription_one_active_subscription_per_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='member_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
