# Generated by Django 6.0.2 on 2026-03-04 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_member_join_date_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 3, 4)),
            preserve_default=False,
        ),
    ]
