# Generated by Django 6.0.2 on 2026-03-08 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_member_age_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('join_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Leave', 'Leave')], default='Active', max_length=10)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym')),
            ],
        ),
    ]
