# Generated by Django 6.0.2 on 2026-03-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_trainer_trainer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='status',
        ),
    ]
